/*
CREATE DATABASE BibliotecaUniversitaria;*/
USE BibliotecaUniversitaria;
/*
CREATE TABLE libro
(
	ID_LIBRO INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    ANIO_PUBLICACIÓN VARCHAR(60) NOT NULL,
    GENERO VARCHAR(40),
    EJEMPLARES INT NOT NULL CHECK (EJEMPLARES >=0),
    ISBN CHAR(13) NOT NULL UNIQUE
    );
    
CREATE TABLE AUTOR
(
	ID_AUTOR INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    NACIONALIDAD VARCHAR(40),
    FEHCA_NACIMINETO DATE,
    EDAD INT 
    );
CREATE TABLE  USUARIOS
(
	ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    TELEFONO CHAR(9),
    FECHA_ALTA DATE NOT NULL DEFAULT (CURRENT_DATE),
    TIPO ENUM('ESTUDIANTE' , 'PROFESOR' , 'EXTERNO') NOT NULL DEFAULT 'ESTUDIANTE'
    );
CREATE TABLE PRESTAMO
(
	ID_PRESTAMO INT NOT NULL,
    ID_USUARIOS INT NOT NULL,
    FECHA_PRESTAMO DATE NOT NULL DEFAULT (CURRENT_DATE),
    FECHA_DEVOLUCION DATE GENERATED ALWAYS AS (DATE_ADD(fecha_prestamo, INTERVAL 7 DAY)) VIRTUAL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    OBSERVACIONES VARCHAR (100)
    );
CREATE TABLE DETALLE_PRESTAMO
(
	ID_PRESTAMO INT NOT NULL, 
    ID_LIBRO INT NOT NULL,
    CANTIDAD INT NOT NULL  CHECK (CANTIDAD > 0)
    );
  */
  ALTER TABLE LIBRO ADD PRIMERY KEY 
    
    
    
    
    
    
    

    
    
    
    
