CREATE DATABASE Ejemplo;
USE Ejemplo;
CREATE TABLE Persona
(
id INT (10) NOT NULL ,
Nombre VARCHAR (20) NOT NULL,
Apellido VARCHAR (20) NOT NULL,
Ciudad VARCHAR (20)
);
ALTER TABLE  persona
ADD PRIMARY KEY (id),
MODIFY COLUMN id INT (10) NOT NULL AUTO_INCREMENT;
